"""descrição da alteração

Revision ID: 286fff34e9e6
Revises: 
Create Date: 2026-06-16 23:21:49.942081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286fff34e9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Agendar_Live_Turma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_turma_agenda', sa.Text(), nullable=True),
    sa.Column('sala_turma_agenda', sa.Text(), nullable=True),
    sa.Column('data_hora_agenda_live', sa.Text(), nullable=True),
    sa.Column('id_aluno_turma_agenda_live', sa.Text(), nullable=True),
    sa.Column('status_agenda_live', sa.Text(), nullable=True),
    sa.Column('tema_agenda_live', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tabela_cliente_vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vendedor', sa.Text(), nullable=True),
    sa.Column('id_cliente', sa.Text(), nullable=True),
    sa.Column('nome_cliente', sa.Text(), nullable=True),
    sa.Column('nome_produto', sa.Text(), nullable=True),
    sa.Column('data_registro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Turma_Aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_admin_Turma', sa.Integer(), nullable=True),
    sa.Column('nome_Turma', sa.Text(), nullable=True),
    sa.Column('tipo_usuario_Turma', sa.Text(), nullable=True),
    sa.Column('id_aluno_Turma', sa.Text(), nullable=True),
    sa.Column('sala_Turma', sa.Text(), nullable=True),
    sa.Column('imagem_perfil_Turma', sa.Text(), nullable=True),
    sa.Column('data_criacao_Turma', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('url_video_Turma', sa.Text(), nullable=True),
    sa.Column('Titulo_video_Turma', sa.Text(), nullable=True),
    sa.Column('licao_video_Turma', sa.Text(), nullable=True),
    sa.Column('adoro_video_Turma', sa.Text(), nullable=True),
    sa.Column('visto_video_Turma', sa.Text(), nullable=True),
    sa.Column('comentario_video_Turma', sa.Text(), nullable=True),
    sa.Column('avaliacao_video_Turma', sa.Text(), nullable=True),
    sa.Column('descricao_video_Turma', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adicionar_nova_aula',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_Turma', sa.Text(), nullable=True),
    sa.Column('id_admin_Turma', sa.Text(), nullable=True),
    sa.Column('tema_video', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('quantidade_visualização_video', sa.Text(), nullable=True),
    sa.Column('quantidade_adoro_video', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('amizades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_turma_convite', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nome_Turma', sa.Text(), nullable=True))
        batch_op.alter_column('valor_deposito',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'none'::text"))
        batch_op.alter_column('conta_deposito',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'none'::text"))

    with op.batch_alter_table('menssagens', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('meus_amigos', schema=None) as batch_op:
        batch_op.alter_column('nossa_sala',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('reacao_produto', schema=None) as batch_op:
        batch_op.alter_column('estado_visualizacao',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('estado_adoro',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reacao_produto', schema=None) as batch_op:
        batch_op.alter_column('estado_adoro',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('estado_visualizacao',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('meus_amigos', schema=None) as batch_op:
        batch_op.alter_column('nossa_sala',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('menssagens', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('amizades', schema=None) as batch_op:
        batch_op.alter_column('conta_deposito',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'none'::text"))
        batch_op.alter_column('valor_deposito',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'none'::text"))
        batch_op.drop_column('nome_Turma')
        batch_op.drop_column('id_turma_convite')

    op.drop_table('adicionar_nova_aula')
    op.drop_table('Turma_Aula')
    op.drop_table('Tabela_cliente_vendedor')
    op.drop_table('Agendar_Live_Turma')
    # ### end Alembic commands ###
